[package]
name = "cryptasm"
version = "0.1.0"
authors = ["dignifiedquire <dignifiedquire@gmail.com>"]

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = { git = "https://github.com/rustwasm/wasm-bindgen" }
# rust-crypto = "*"
aes = "^0.1"
block-modes = "*"
